#index:
#    path: /
#    controller: App\Controller\DefaultController::index

user_list:
    path: /api/user
    controller: App\Controller\UserController:indexAction
    methods: [GET]

user_create:
    path: /api/user
    controller: App\Controller\UserController:createAction
    methods: [POST]